server.port=8091
spring.application.name=api-gateway

# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8079
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/users/**

# ORDER SERVICE(CART AND  ORDER)
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**,/cart/**

# INVENTORY SERVICE
spring.cloud.gateway.routes[2].id=inventory-service
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/inventory/**

# PAYMENT SERVICE
spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/payments/**

logging.level.org.springframework.cloud.gateway=DEBUG
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUTG9naW5UZXN0MTIzNDU2